// GENERATED by build.js. Do not edit by hand.
module.exports = {
  "catalog": {
    "kids-dress": {
      "name": "The Lydia Dress",
      "base": 4000,
      "sizes": {
        "0-3m": 4000,
        "3-6m": 4000,
        "6-9m": 4000,
        "9-12m": 4000,
        "12-18m": 4500,
        "18-24m": 4500,
        "2-3y": 4500,
        "3-4y": 4500,
        "4-5y": 5000,
        "5-6y": 5000,
        "6-7y": 5500,
        "7-8y": 5500
      },
      "sizeLabels": {
        "0-3m": "0 to 3 months",
        "3-6m": "3 to 6 months",
        "6-9m": "6 to 9 months",
        "9-12m": "9 to 12 months",
        "12-18m": "12 to 18 months",
        "18-24m": "18 to 24 months",
        "2-3y": "2 to 3 years",
        "3-4y": "3 to 4 years",
        "4-5y": "4 to 5 years",
        "5-6y": "5 to 6 years",
        "6-7y": "6 to 7 years",
        "7-8y": "7 to 8 years"
      }
    },
    "quilted-bag": {
      "name": "Quilted Stroller Bag",
      "base": 5000,
      "sizes": {},
      "sizeLabels": {}
    },
    "quilted-bag--embroidery": {
      "name": "Embroidery for Quilted Stroller Bag",
      "base": 1000,
      "sizes": {},
      "sizeLabels": {},
      "embroideryAddon": true,
      "maxLength": 30
    },
    "bible-bag": {
      "name": "Bible Accessory Bag",
      "base": 2500,
      "sizes": {},
      "sizeLabels": {}
    },
    "bible-bag--embroidery": {
      "name": "Embroidery for Bible Accessory Bag",
      "base": 1000,
      "sizes": {},
      "sizeLabels": {},
      "embroideryAddon": true,
      "maxLength": 30
    }
  },
  "fabricMap": {
    "black-tan-check": "Black & Tan Homespun Check Cotton Fabric",
    "black-white-gingham": "Black & White Gingham Homespun Cotton Fabric",
    "black-white-gray-plaid": "Black, White & Gray Homespun Plaid Cotton Fabric",
    "blue-dandelion": "Blue Dandelion Cotton Calico Fabric",
    "boho-blender": "Boho Blender Cotton Calico Fabric",
    "brown-plaid": "Brown & White Plaid Cotton Fabric",
    "brown-diamond": "Brown Diamond Print Cotton Calico Fabric",
    "pink-buffalo-plaid": "Buffalo Plaid Cotton Calico Fabric",
    "red-black-buffalo": "Buffalo Plaid Cotton Calico Fabric — Red & Black",
    "clouds-dots": "Clouds & Dots Cotton Calico Fabric",
    "cream-sunflower": "Cream Sunflower Cotton Calico Fabric",
    "earth-botanical": "Earth Botanical Cotton Calico Fabric",
    "earth-tone-floral": "Earth Tone Floral Cotton Calico Fabric",
    "farm-floral-ditzy": "Farm Floral Ditzy Cotton Calico Fabric",
    "gingham-ducks": "Gingham Ducks Cotton Calico Fabric",
    "green-cream-polka": "Green & Cream Polka Dot Cotton Calico Fabric",
    "green-daisy": "Green Daisy Cotton Calico Fabric",
    "green-trendy-floral": "Green Trendy Floral Cotton Calico Fabric",
    "homespun-brown": "Homespun Brown Cotton Fabric",
    "homespun-plaid": "Homespun Plaid Cotton Fabric",
    "ivory-gray-stripes": "Ivory & Gray Striped Cotton Calico Fabric",
    "light-blue-denim": "Light Blue Denim Cotton Calico Fabric",
    "light-brown-red-floral": "Light Brown & Red Tiny Floral Cotton Calico Fabric",
    "mauve-floral": "Mauve Floral Cotton Calico Fabric",
    "mauve-rose-textured": "Mauve Rose Textured Cotton Calico Fabric",
    "mini-floral": "Mini Floral Cotton Calico Fabric",
    "muted-rainbow": "Muted Rainbow Cotton Calico Fabric",
    "light-nautical": "Nautical Map Cotton Calico Fabric",
    "navy-coral-suns": "Navy & Coral Suns Cotton Calico Fabric",
    "navy-nautical": "Navy Nautical Map Cotton Calico Fabric",
    "painted-flowers": "Painted Flowers Cotton Calico Fabric",
    "prairie-ecru-stripes": "Prairie Girl Striped Ecru Cotton Calico Fabric",
    "red-cream-distressed": "Red & Cream Distressed Cotton Calico Fabric",
    "red-white-gingham": "Red & White Gingham Cotton Calico Fabric",
    "red-mini-floral": "Red Mini Floral Cotton Calico Fabric",
    "rosebuds": "Rosebuds Cotton Calico Fabric",
    "rust-floral": "Rust Floral Cotton Calico Fabric",
    "strawberries": "Strawberries Cotton Calico Fabric",
    "tan-stripes": "Tan & White Striped Dyed Yarn Essex Linen Fabric",
    "tea-dye-bee": "Tea Dye Bee Cotton Calico Fabric",
    "tiny-pink-hearts": "Tiny Pink Hearts Cotton Calico Fabric",
    "tonal-starburst": "Tonal Starburst Cotton Calico Fabric",
    "unbleached-muslin": "Unbleached Premium Muslin Fabric",
    "white-black-polka": "White & Black Polka Dot Cotton Calico Fabric",
    "white-black-ticking": "White & Black Ticking Striped Cotton Calico Fabric",
    "wine-tan-check": "Wine & Tan Check Homespun Cotton Fabric",
    "yellow-scroll": "Yellow Scroll Print Cotton Calico Fabric"
  },
  "shipping": {
    "flatRate": 600,
    "freeOver": 7500,
    "localPickup": false,
    "localPickupLabel": "Local pickup in Ottumwa",
    "standardLabel": "Standard shipping (US)",
    "standardEstimate": "3 to 5 business days after your piece is made",
    "countries": [
      "US"
    ],
    "note": "Default rates. Confirm the real numbers with Olivia before launch."
  },
  "tax": {
    "enabled": false,
    "rate": 7,
    "label": "Sales tax (Iowa 7%)",
    "note": "Ottumwa is 6% Iowa state tax plus a 1% local option tax, so 7.0% combined. Left OFF by default because LivLocal must hold an Iowa sales tax permit before collecting tax. Confirm with the Iowa Department of Revenue, then set enabled to true."
  },
  "site": {
    "name": "LivLocal",
    "contactEmail": "liv@livlocal.studio"
  }
};
