// GENERATED by build.js. Do not edit by hand.
module.exports = {
  "catalog": {
    "kids-dress": {
      "name": "Handmade Kids Dress",
      "base": 4000,
      "sizes": {
        "0-3m": 4000,
        "3-6m": 4000,
        "6-9m": 4000,
        "9-12m": 4000,
        "12-18m": 4500,
        "18-24m": 4500,
        "2-3y": 4500,
        "3-4y": 4500,
        "4-5y": 5000,
        "5-6y": 5000,
        "6-7y": 5500,
        "7-8y": 5500
      },
      "sizeLabels": {
        "0-3m": "0 to 3 months",
        "3-6m": "3 to 6 months",
        "6-9m": "6 to 9 months",
        "9-12m": "9 to 12 months",
        "12-18m": "12 to 18 months",
        "18-24m": "18 to 24 months",
        "2-3y": "2 to 3 years",
        "3-4y": "3 to 4 years",
        "4-5y": "4 to 5 years",
        "5-6y": "5 to 6 years",
        "6-7y": "6 to 7 years",
        "7-8y": "7 to 8 years"
      }
    },
    "quilted-bag": {
      "name": "Quilted Bag",
      "base": null,
      "sizes": {},
      "sizeLabels": {}
    },
    "bible-bag": {
      "name": "Bible Bag",
      "base": null,
      "sizes": {},
      "sizeLabels": {}
    }
  },
  "fabricMap": {
    "fabric-01": "Fabric 01",
    "fabric-02": "Fabric 02",
    "fabric-03": "Fabric 03",
    "fabric-04": "Fabric 04",
    "fabric-05": "Fabric 05",
    "fabric-06": "Fabric 06",
    "fabric-07": "Fabric 07",
    "fabric-08": "Fabric 08",
    "fabric-09": "Fabric 09",
    "fabric-10": "Fabric 10"
  },
  "shipping": {
    "flatRate": 600,
    "freeOver": 7500,
    "localPickup": true,
    "localPickupLabel": "Local pickup in Ottumwa",
    "standardLabel": "Standard shipping (US)",
    "standardEstimate": "3 to 5 business days after your piece is made",
    "countries": [
      "US"
    ],
    "note": "Default rates. Confirm the real numbers with Olivia before launch."
  },
  "tax": {
    "enabled": false,
    "rate": 7,
    "label": "Sales tax (Iowa 7%)",
    "note": "Ottumwa is 6% Iowa state tax plus a 1% local option tax, so 7.0% combined. Left OFF by default because LivLocal must hold an Iowa sales tax permit before collecting tax. Confirm with the Iowa Department of Revenue, then set enabled to true."
  },
  "site": {
    "name": "LivLocal",
    "contactEmail": "trevan@c2cmedia.studio"
  }
};
